#!/usr/bin/env node

/* eslint no-console: 0 */
'use strict';

const program = require('commander');
const scraper = require('./scraper.js');
const report = require('./report.js');
const format = require('./format.js');
const helpers = require('./helpers/helpers.js');


program
    .version('1.0.0-alpha.1');

program
    .command('stalk [user_id]')
    .description('Collect data and monitor updates for user with ID=user_id')
    .action(user_id => {
        scraper.work(user_id);
    });

program
    .command('report [user_id]')
    .description('Generate a report/summary on data collected about the user with ID=user_id')
    .option('-t, --type [type]', 'Generate a specific report. Options: general, music.')
    .action((user_id, options) => {
        const type = options.type || 'music';
        console.log(`\nRequested ${type} report for user with ID=${user_id}\n`);
        report(type, user_id)
            .then(data => {
                let formatter_type = `report${helpers.capitalize(type)}`;
                console.log(format(formatter_type, data));
                process.exit();
            });
    });

program
    .command('help')
    .description('Display information about accepted commands and options')
    .action(() => {
        program.help();
        process.exit();
    });

program.parse(process.argv);

// let missing_command_text = 'Unknown command.\nUse `vkstalk help` to see the list of available commands and options';
// process.stdout.write(missing_command_text);
// process.exit();
