#!/usr/bin/env node

/* eslint no-console: 0 */
'use strict';

const program = require('commander');
const cluster = require('cluster');

const format = require('./format.js');
const helpers = require('./helpers/helpers.js');
const actions = require('./actions');


program
    .version(require('../package.json').version);

program
    .command('stalk [user_id]')
    .description('Collect data and monitor updates for user with ID=user_id')
    .action(actions.stalk);

program
    .command('report [user_id]')
    .description('Generate a report/summary on data collected about the user with ID=user_id')
    .option('-t, --type [type]', 'Generate a specific report. Options: general, music.')
    // .option('--raw-data', 'Return raw data, without formatting')
    .action(actions.report);

program
    .command('help')
    .description('Display information about accepted commands and options')
    .action(() => {
        program.help();
        process.exit();
    });

program.parse(process.argv);

// let missing_command_text = 'Unknown command.\nUse `vkstalk help` to see the list of available commands and options';
// process.stdout.write(missing_command_text);
// process.exit();
