#!/usr/bin/env node

/* eslint no-console: 0 */
'use strict';

const program = require('commander');
const actions = require('./actions');


program
    .version(require('../package.json').version)
    .arguments('<cmd> [env]');

program
    .command('stalk <user_id>')
    .description('Collect data and monitor updates for user with ID=user_id')
    .action(actions.stalk);

program
    .command('report <user_id>')
    .description('Generate a report/summary on collected data about the user with ID=user_id')
    .option('-t, --type <type>', 'Report type', /^(general|music|updates)$/, 'music')
    .option('--period <[from]..[to]>', 'Datetime range from..to. Datetime format: yyyy.mm.dd HH:MM:ss:ms')
    // .option('--raw-data', 'Return raw data, without formatting')
    .action(actions.report);

program
    .command('help')
    .description('Display information about accepted commands and options')
    .action(() => {
        program.help();
        process.exit();
    });

program.parse(process.argv);
